Prefix = "example"

[Connection]
URI = "postgres://user:pass@localhost/{}?sslmode=disable"
Database = "maintainance" 


[Migration]
Directory = "./migrations" 
Format = "![0-9]{15}_"
Command = "migrate up --database {}"
