Prefix = "example"

[Connection]
URI = "postgres://user:pass@localhost/{}?sslmode=disable"
Database = "maintainance" 


[Migration]
Directory = "./example/migrations" 
Format = "^[0-9]{4}_"
Command = "migrate up --database {}"
