Prefix = "dbtm"

[Connection]
URI = "postgres://postgres@localhost/{}?sslmode=disable"
Database = "postgres" 


[Migration]
Directory = "./example/migrations" 
Format = "^[0-9]{4}_"
Command = [ "./example/migrate", "{}" ]
